- name: upping to date all os packages
  yum:
    name: "*"
    state: latest
- name: installing git client
  yum:
    name: git
    state: latest
- name: host config ansible
      lineinfile: 
        dest: /etc/hosts
        line: "{{item}}"
        state: present
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01