---
- name: server java app configuration
  hosts: app01

  user: vagrant
  become: yes

  vars:
    dbhost: "db01"
    dbname: "notesdb"
    dbusername: "root"
    dbpassword: "notesdevops"
  tasks:
    - name: add user to the app
      user:
        name: app
        comment: app user
        uid: 500
    - name: maven downloading
      get_url: 
        url: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.1.0/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/apache-maven-3.1.0-bin.tar.gz
    - name: Unzip maven package
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.1.0-bin.tar.gz
        dest: /opt/
        remote_src: yes
    - name: jre installing
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: dir creation
      file: 
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: installing git client
      yum:
        name: git
        state: latest
    - name: git clone app repository
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: config pom.xml 
      template: 
        src: pom.xml
        dest: /opt/notes/pom.xml
    - name: config property file
      template: 
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: generate app package
      command: /opt/apache-maven-3.1.0/bin/mvn -f /opt/notes/pom.xml package
      become_user: app
    - name: manage package version
      shell: 
        cmd: /opt/apache-maven-3.1.0/bin/mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version
    - name: systemd config
      template: 
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
        owner: root
        group: root
        mode: '0600'
      notify: reload daemon
    - name: start service
      service:
        name: notes
        state: restarted
  roles:
    - default-os-config
  handlers: 
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes
        



        
