---
- name: database server configuration
  hosts: db01
  
  user: vagrant
  become: yes
  vars_files: 
    - vars/main.yml
  vars:
    dbname: "notesdb"
    dbusername: "root"
    dbpassword: "notesdevops"
  roles:
    - default-os-config
    - role: geerlingguy.mysql   

      
